### ISSUE TITLE
Error HM5158 While Indexing

### ISSUE THREAD

**Issue by bighossbiz** [hmailserver/hmailserver#11]
See for all details: https://www.hmailserver.com/forum/viewtopic.php?f=7&t=26860&start=0

While doing investigation, found hMail is choking on UTF-8 characters that appear to be unknown while indexing. Seems like source OS generating these characters are apple based - not enough information from the sources yet to determine definitively.
Email sources are from facebook, salary.com, and iOS devices.

Server OS: is win2k3

An example message header (with some information redacted for anonymity) that produced the symptoms explained.

Content-Type: text/html;
        charset=utf-8
Content-Transfer-Encoding: quoted-printable
Subject: =?utf-8?Q?Email_Subject=F0=9F=90=B0?=
From: 
X-Universally-Unique-Identifier: DD1A41ED-2F25-41E8-ACA9-FFFDE157C8FD
X-Uniform-Type-Identifier: com.apple.mail-note
Message-Id: <9312EB10-A0CC-4527-BDC3-0360E1E619C9@email.domain>
Date: Fri, 27 Jun 2014 02:21:29 +0800
X-Mail-Created-Date: Tue, 24 Jun 2014 01:46:09 +0800
Mime-Version: 1.0 (iOS/7.1.1 \(11D201\) dataaccessd/1.0)

**Comment by japi** [comment]
I have validated that the hMailServer Versions 2.6.1+ together with MySQL 5.5.3+ can store metadata with utf8mb4 character set / collation.
I used the following SQL command (generated by phpMyAdmin):
`ALTER TABLE 'hm_message_metadata' CHANGE 'metadata_subject' 'metadata_subject' VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;`
That Column was the only one having errors in my setup on a daily basis.
I sent test messages with one of the great and usefull new unicode characters in the subject: 💩 ([pile of poo](http://www.fileformat.info/info/unicode/char/1F4A9/index.htm))
Everything worked like a charm. It also showed up in phpMyAdmin nice and clean and tidy.
I tried to reindex all messages by Clearing the index, Disabling and Enabling the Index - all without success, the index wouldn't go beyond around 700 items. After restarting the hMailServer service, the index finally started to rebuild completely. Before doing the reindex, the index was missing 6 items (most likely some with 4 byte characters), now i am back to 100%, no items missing. (maybe a restart would have done without clearing the index?)

I just hope this workaround/fix wont break with future hMailServer versions, which may have an official fix to this bug :-)

@martinknafve: If you do the detection of the mysql version to determine if you can use utf8mb4 (as you said [here](https://github.com/hmailserver/hmailserver/issues/11#issuecomment-53980291) - isn't it possible to send that ALTER TABLE statement once, if utf8mb4 is supported?

PS: For anyone having trouble updating from MySQL 5.1 to newer versions: I had the following issue: After using the standard windows installer to "upgrade", mysql just crashed without any error message (yes, no outout, no log, no nothing). I then went back to my backup. I discovered that some update in the past (to that version 5.1) was not complete - the binaries were the new ones, but the data files were never updated. The issue was easy to resolve by using mysql_upgrade before updating to 5.6+ (if i remember correctly). I must have missed that some years ago... (Though I thought the graphical installer would not just replace the binaries when installed over an existing installation - maybe I did not use the gui installer? never mind, case closed :-)
