### ISSUE TITLE
Minor log issue

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#119]
https://www.hmailserver.com/forum/viewtopic.php?f=10&t=28506

**Comment by martinknafve** [comment]
I've just changed the wording in the log slightly.

Rather than logging "Ceating session 1", hMailServer now logs "Pre-creating session 1". Pre-creation of sessions happens before users have actually connected to the server. So the error was technically correct before as well, but clearly a bit unclear...
