### ISSUE TITLE
Email address validation not conforming to RFC821 to allow "quoted" local-part

### ISSUE THREAD

**Issue by jimimaseye** [hmailserver/hmailserver#127]
RFC821 says it that quoted local-part is allowed for an email address.  Page 30 : https://tools.ietf.org/html/rfc821#page-30:

      <reverse-path> ::= <path>
         <path> ::= "<" [ <a-d-l> ":" ] <mailbox> ">"
            <mailbox> ::= <local-part> "@" <domain>
               <local-part> ::= <dot-string> | <quoted-string>
                  <quoted-string> ::=  """ <qtext> """

eg,  "geoff"@domain.com

Hmailserver code 'IsValidEmailAddress' clearly states (coded as):

      // - Don't allow < or > or " anywhere.
      //
      String regularExpression = "[^<>\" ]+@[^<>\" ]+\\.[^<>\" ]+";

Although its not common to use, it has caused problems for some users and it should conform to RFC.

https://www.hmailserver.com/forum/viewtopic.php?p=179931#p179931

**Comment by jimimaseye** [comment]
Maybe it should be::

    // - Don't allow < or > or ". (" allowed local only).
    //
    String regularExpression = "[^<> ]+@[^<>\" ]+\\.[^<>\" ]+";

(Also: is the double \\ really necessary for DOT separator?  Shouldnt it be \.   ? )

**Comment by martinknafve** [comment]
This seems like low enough prio that I won't include a fix for this in 5.7.

**Comment by jimimaseye** [comment]
I provided (above) what I believe is the regexp change to allow the quotes (obviously requiring your overall double check) and as we have people already suffering from this incompliance to the RFC rule I thought it might be a quick enough fix and more immediate.

**Comment by martinknafve** [comment]
Alright, I'll have a look at it later today.

Martin
Den 28 apr 2016 11:48 skrev "jimimaseye" <notifications@github.com>:

**Comment by jimimaseye** [comment]
Cheers Martin.

FYI (if it helps) I quote RFC2822 3.4.1 [here](https://www.ietf.org/rfc/rfc2822.txt) (detailing the 'addr-spec' for email address)

> addr-spec       =       **local-part** "@" domain
> 
> **local-part      =**       dot-atom / **quoted-string** / obs-local-part
> 
> domain          =       dot-atom / domain-literal / obs-domain
> 
> domain-literal  =       [CFWS] "[" *([FWS] dcontent) [FWS] "]" [CFWS]
> 
> dcontent        =       dtext / quoted-pair
> 
> dtext           =       NO-WS-CTL /     ; Non white space controls


This spec makes valid the following example formats:
john @host.net
john@[10.0.3.19]
"John Gate"@host.net
"John Gate"@[10.0.3.19]

So I think the regexp modification in my 2nd post (removing the quote restriction in the 'local' part) should be sufficient.

**Comment by martinknafve** [comment]
This was a more complicated than just altering the regex. For example, an email address can contain pretty much any character, many which are not permitted in folder names in NTFS. This cause a problem if hMailServer will try to create a user directory with these characters.

What I've implemented is the following:

hMailServer can receive email from, and send email to addresses with quoted mailbox-part containing spaces. In hMailServer, you cannot set up these quoted mailboxes as user accounts (since this would cause an issue when creating user folder in data directory). A workaround to that is to set up an alias with quoted mailbox-part, and then forward to a user account without.

It's fixed in the next 5.6 and 5.7-builds.
