### ISSUE TITLE
'Verify remote server SSL/TLS certificates' seems to not work

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#139]
Well the verify part seems to work, just that the connection isn't dropped if the certificate fails.

Have sent some logs to you Martin...

Not that it really matters, because I have some important mail to these two recipients. I would need to turn that checkbox off if it worked correctly.

**Comment by martinknafve** [comment]
In most cases, certificate verification isn't really useful for SMTP because a huge part of all mail servers are configured with invalid certificates.

If you select "Use STARTTLS if available", that means that the usage of "STARTTLS (Optional)" will be enabled. In this mode, and if certificate verification is enabled, then certificate validation will be performed, and the result will be logged, but if the certificate verification fails the connection will still be kept alive. This mode is described briefly here under Connection security types:

https://www.hmailserver.com/documentation/v5.6/?page=reference_connection_security

So this behavior is actually as-intended. Prior to this behavior (in earlier betas), hMailServer did actually drop the connections with invalid certificates, but that configuration made hMailServer useless since so many connections were dropped.

**Comment by OutbackMatt** [comment]
"...because a huge part of all mail servers are configured with invalid certificates."
Kind of defeats the point of encryption I guess.

Close this issue off...I'll think about this a while longer.

Thanks for the prompt response.

**Comment by martinknafve** [comment]
It defeats it to some extent. 

If you set up a SMTP route or specify a SMTP relayer, you can then choose that TLS should be required rather than optional. Then a proper certificate will be required. 

There are benefits with TLS when doing "ad-hoc" SMTP deliveries as in your case as well. With your current configuration, if someone at your Internet Service Provider wants to listen in on your communication, he can't passively check their server logs to see who you've been communicating with, because your communication will be encrypted. Instead, he has to set up active listening using his own invalid certificate. This type of active listening is more likely to be spotted by some one, which then reduces the risk that he would do that. So in short, your current set up will stop "passive listening" of your communication, and it will be active listening more risky for anyone who tries.
