### ISSUE TITLE
Add SMTP option to allow lines longer then 998 characters

### ISSUE THREAD

**Issue by rhgrant** [hmailserver/hmailserver#146]
Reference https://www.hmailserver.com/forum/viewtopic.php?f=7&t=29207
Messages sent to hMailServer with lines longer then 998 characters are rejected.
Per RFC5322 https://datatracker.ietf.org/doc/rfc5322/?include_text=1 section 2.1.1, there is a recommendation that these long lines be accepted...

> The 998 character limit is due to limitations in many implementations
>    that send, receive, or store IMF messages which simply cannot handle
>    more than 998 characters on a line.  **Receiving implementations would
>    do well to handle an arbitrarily large number of characters in a line
>    for robustness sake.**  However, there are so many implementations that
>    (in compliance with the transport requirements of [RFC5321]) do not
>    accept messages containing more than 1000 characters including the CR
>    and LF per line, it is important for implementations not to create
>    such messages

Add an option under the SMTP settings RFC Compliance tab to "Allow lines longer the 998 characters" or just make this the default behavior.

**Comment by visualperception** [comment]
The first paragraph of that section which has been omotted from above quote states:

>    There are two limits that this specification places on the number of
>    characters in a line.  Each line of characters MUST be no more than
>    998 characters, and SHOULD be no more than 78 characters, excluding
>    the CRLF.

Note the "MUST". 

when you factor that in I read the whole section as saying you may want to allow incoming external mail with >998+CRLF through so that it is not rejected but you should never allow outgoing mail TEXT lines to be longer than 998+CRLF.

incidentally I looked to see what my mobile phone texting limit is and it allows 2000 chs which seems to be a lot more than what the standard says should be allowed for IMF messages.

**Comment by TheSleepingFox** [comment]
This feature would be good to have atleast on a receiving implementation, as using this as a relay and then using Vbscript to parse the incoming email before relaying would allow us to use this to clean emails from bad third party software.

**Comment by martinknafve** [comment]
Since hMailServer is no longer being actively developed, enhancements will only be included if authored as a PR with automated tests.
