### ISSUE TITLE
Sometimes icoming files stay at data directory

### ISSUE THREAD

**Issue by SteffenM-DE** [hmailserver/hmailserver#155]
Normally an incoming mail is created at the data directory and after processing it would be deleted. Sometimes this files at data directory stay there after processing. These files not shown at the Delivery Queue Windows anymore and as far as I know the mails are processed and delivered.

So I think maybe there is a timing problem so sometimes the file is still locked and hMS could not delete them. I'm monitoring that directory and here it happens several times a week.

**Comment by OutbackMatt** [comment]
I still think this is caused by not removing the data directory from real time AV scanning

**Comment by martinknafve** [comment]
Since hMailServer is no longer under active development, and this is a very old issue (which does not seem to affect many people), I will close this issue without action. I know of one way to reproduce this issue (related to long email addresses). If you know a way to reproduce this issue then please add steps to reproduce and I can look into it.
