### ISSUE TITLE
Multiple eml with same recipients

### ISSUE THREAD

**Issue by Vauxite** [hmailserver/hmailserver#161]
Hello

**Problem**
Sending one mail to 60 different recipients (all within the same domain).
A centos server running postfix relay the mail to a windows machine running hMailserver 5.6.4-B2283.
 hMailserver receive the mail by smtp.
 When the hMailserver has finnished parsing the mail. There is two .eml files both containing a complete list of the 60 recipients.
In previous version (4.3) the recipients were split between the files (Maximum of 50 unique per file).

**Additional Information**
catch.mydomain.com is added with catchall postmaster@catch.mydomain.com.
Sent to email in the following format "TestMessage[0-5][0-9]@catch.mydomain.com"

**Versions**
New server: hMailserver 5.6.4 -B2283
Old server: hMailserver 4.3-b248
No scripts on either of them.

**Comment by martinknafve** [comment]
To me this behavior sounds correct. The .eml file does not contain the SMTP envelope recipients, only the recipients as specified in the To header in the email message headers. The actual recipients of the message (envelope recipients) are stored in the database and not in the .eml file.

If hMailServer is configured to limit batches to 50 recipients, and you send to 60 recipients, you should see two .eml files with 60 recipients listed in each .eml (in the "To" header). If you look at the recipients in the database, you would then see 50 recipients for the first and 10 for the second.

I'm pretty sure this is the behavior which existed in 4.x as well.

Do you experience a problem?

**Comment by Vauxite** [comment]
Yes I experience a problem where the behavior has changed between the versions. It does make sense the to-field in the email would show all the recipients. However in version 4.3, I believe smtp envelope was used to populate the to-field.

I haven't explicitly configured the hmailserver to limit batches to 50. That is probably in the postfix server (which is unchanged during the test I've performed).

If this is as intended. Is it possible to write a script (not asking for one) that would use the SMTP envelope recipients to populate the email to-field? Or what would be the best approach.

And thank you for taking the time to help me resolving this issue!

**Comment by martinknafve** [comment]
The SMTP envelope recipients were never used to populate the To field. The To field has always been populated by the sending email client - hMailServer knows who the email should be sent to on the hMailServer server, but it does not know which recipients should go into the To field or which should go in to CC or BCC. Nor does the SMTP envelope contains recipients which exists on other servers - for example, if you send an email from gmail to 2 recipients, one on a hMailServer instance and one on  a Hotmail instance, then the To MIME header will contain both recipients, but when the email reaches hMailServer the SMTP envelope will only contain 1.

I'm still not sure what problem you are trying to solve or what the issue is. If you have an email client which sends an email, then that email client should be adding all the recipients to the To field in the email message. This is not the job of the mail server and implementing it in the mail server would break certain things (for example it would break the handling of BCC, since all recipients would then be added to the To field, even if they were intended to be kept secret)
