### ISSUE TITLE
Spam protection MTA Blackllst ?

### ISSUE THREAD

**Issue by visualperception** [hmailserver/hmailserver#165]
Is it possible to add a blacklist option to the anti spam features.
I know/think blacklist has been asked for before but what I'm thinking is a server blacklist so for the actual sending server the received header in incoming mail would contain something like:

Received: from **mail1.bemta3.messagelabs.com** ([195.245.230.34]

It is the mail server name I would like a blacklist option for. The IP would be good too but primarily the sending mail server name and it should be allowed to use wildcard so that you could enter 
*.messagelabs.com or perhaps better if oClient.HELO contains xxxxxx so you can put as much or little into it for the check.

many marketing companies use amazon or gmail and trying to block their IPs is waste of time since they change so often and you can end up blocking wrong people.

So this is really a blacklist on what is sent in helo/ehlo (oClient.HELO).

**Comment by martinknafve** [comment]
Since hMailServer is no longer under active development, this is a very old issue and is a request for an enhancement (rather than a request to fix a critical bug), I will close this without action. I realize that you may still want this fixed, but I don't want to give the false impression that this is something being worked on.
