### ISSUE TITLE
[LANGUAGE].INI not being fully read/adhered for Hmailadmin.exeon AUTOBAN screen

### ISSUE THREAD

**Issue by jimimaseye** [hmailserver/hmailserver#180]
(I discovered this whilst trying to deal with issue 179)

SUMMARY
Changing the auto-ban literals in the ENGLISH.INI file **stops all other languages** from displaying their correct language versions (and always defaults to a hard-coded ENGLISH text) even when english is not the preferred language.  In other words: AUTOBAN screen does not display the _language_.ini dependant literal (641 and 642), and seems to be hard-coded and always in english **IF THE ENGLISH.INI has been changed**.

ie,
1, it ALWAYS displays in English (eg, even though SWEDISH (or another language) is selected and other literals are displayed in swedish as per the language setting, that screen always shows ENGLISH hard-coded words of those same literals were changed in the ununsed English.ini file.

2, this also applies to the english.ini file:  eg, whatever is written in the file is ignored and always fixed as 

**Max invalid logon attempts

Minutes before reset

Minutes to auto-ban**

even if the english.ini file has different wordings for those literals.

![LanguageConfusion](https://www.hmailserver.com/forum/download/file.php?id=2951&mode=view)

FULL graphical display showing the problem here: https://www.hmailserver.com/forum/viewtopic.php?f=10&t=29872

Bizarre!

**Comment by martinknafve** [comment]
Not sure I follow entirely, because this seems to be as-designed.

When hMailServer starts, it creates a map of English -> <OtherLanguage> translations, so for example English -> Swedish, English -> Italian.

When you bring up hMailServer Administrator, it will ask the hMailServer service for the Italian translation of the sentence "Max invalid logon attempts". How does it know that it should do the lookup for this string? It knows, because this is the string specified in the UI. If hMailServer cannot find the translation of the sentnce "Max invalid logon attempts", it will default to english.

The default language in hMailServer is english. You can't change it by editing the english ini file without also updating the textblocks in hMailServer Administrator. If you only change the english.ini, hMailServer won't find the translation of "Minutes before reset", and will default to the hard-coded sentence.

**Comment by jimimaseye** [comment]
Ah, so the key here is "you cant change the ENGLISH wordings in 
ENGLISH.INI".

So english-language displays are always hard-coded and foreign language 
displays rely on the english.ini to be unchanged in order it then finds 
the foreign equivalent?

(I thought maybe all text on display would have been had a text ' number 
code' ("literal") for each position which is then looked up in the 
relevant [language].ini file and didnt think there is any hard-coding.)

Have I understood you correctly?

**Comment by martinknafve** [comment]
Yes, you've understood it correctly.

**Comment by OutbackMatt** [comment]
Seems really counter intuitive...
I was thinking that the english.ini could be changed to have an effect on the GUI too

**Comment by martinknafve** [comment]
This is as-designed and won't be changed in the near future, so I'm closing this for now.
