### ISSUE TITLE
hMailServer.sdf - password clarification

### ISSUE THREAD

**Issue by Dravion** [hmailserver/hmailserver#198]
Iam not quite sure you understand me correctly.
 I want to open "hMailServer.sdf" with Visual Studio SQL CE Database Editor or Powershell without even touch hMailServers COM Interface. 

*After hMailServer i noticed the following.
1) Installing on MySQL, the DB-User/Password can be setup with MySQL builtin Admin (mysql.exe)
2) Installing on MSSQL-Server, the DB-User/Password can be setup DB-Management Stdudio
3) Installing on Postgres, the DB-User/Password can be setup ip with PgAdmin3

If it comes to MS-SQL Compact 3.5 or 4.0 i cannot open 
C:\Program Files (x86)\hMailServer\Database\hMailServer.sdf with tools like CEQuery or SQLIteCE
Toolbox because it sasys the provided Password (setup by the Inno-Setup installer for a MSSQL CE
Installation is wrong.

However: i used DecryptBlowfish.vbs to get the correct password for hMailServer.sdf  but the script
returns a string by providing hMailServers password but if i use this encrypted string as Password in
an OLEDB String like this_: Data Source=C:\Program Files (x86)\hMailServer\Database\hMailServer.sdf;Password=RòYpç'  i get a .NET Format initialization Error.

Ok, make long story short - what is the Password for hMailServer.sdf ?
On which point is the password  for hMailServer.sdf is set durning Inno Setup Installation?

**Comment by martinknafve** [comment]
During installation, InnoSetup auto-generates a random password. hMailServer then creates the database hMailServer.sdf with this password and writes the blowfish-encrypted password to hMailServer.ini.

The password contains only characters and numbers, no special characters. So you getting a password with special characters is odd.

Just to make it clear:

1) Run DecryptBlowfish.vbs
2) Enter your hMailServer Administrator password, as entered during the installation, for example secret123
3) Enter the encrypted password, as found under the [Database] section in hMailServer.ini, for example ec3a24b75bc26d9ee498f186efd8586f

If you enter a incorrect value in step 1 or step 2 (just an additional space before or after is enough) then you might see a decrypted password containing special characters (since the proper password can't be encrypted)

I just tested this on a clean 5.6 installation and it worked fine. If it still does not work for you, please let me know what version you are on and I can test on the same.

**Comment by Dravion** [comment]
perfect, now it works, thx

**Comment by jwdonahue** [comment]
Dravion, can this issue be closed now?

**Comment by Dravion** [comment]
Sorry for my late response. Yeah, it can be closed

**Comment by gianniskapouekei** [comment]
Hi...i used install Microsoft SQL Server 2008 Studio Express to connect in the databse. because many users can't remember the password how i can find the decrypted password in the database and after i run the script to dectypted the password. sorry for my english..thanks very much.
