### ISSUE TITLE
Set email header in OnSMTPData should rather fail

### ISSUE THREAD

**Issue by estradis** [hmailserver/hmailserver#232]
When an email header is set in OnSMTPData, the email will become unreadable. 
See details and example in [https://www.hmailserver.com/forum/viewtopic.php?f=10&t=31532]

Therefore any attempt to set email header in OnSMTPData should fail and result a script error.

**Comment by martinknafve** [comment]
Since hMailServer is no longer under active development, and this is a very old issue (which does not seem to affect many people), I will close this issue without action. I realize that you may still want this fixed, but I don't want to give the false impression that this is something being worked on.

**Comment by estradis** [comment]
I can live with that! 

In the meantime we migrated from hMailServer to M365 because in the end the problems became too big. I already knew from the community that there was no active further development. In this context, I had no more expectations of the developers for a long time, neither here, nor in the community. You are welcome to close everything. I am no longer active in any way regarding hMailServer.

@martinknafve You have created something great, but unfortunately not perfect. Nevertheless, many thanks to you for this product and all the best on your further life.
