### ISSUE TITLE
'May be vulnerable to TLS POODLE attack'

### ISSUE THREAD

**Issue by fzanuzzo** [hmailserver/hmailserver#246]
To whom it may interest,

 COMODO SSL Analyzer (https://sslanalyzer.comodoca.com) signs hmailserver 'may be vulnerable to TLS POODLE attack' even after SSL 3.0 has been disabled, only high/medium-security TLS cyphers are chosen and 'Verify remote server SSL/TLS certificates' is kept enabled.

 P. S. : However, IIS and nginx are not shown as having the same kind of issue by the cited SSL analyzer...

 Att, Felipe S. Zanuzzo

**Comment by martinknafve** [comment]
I assume the page tells you that SSL v3 is disabled but that TLS 1.0->1.2 "may be vulnerable"? I ran the check for Gmail's email server (gmail-smtp-in.l.google.com) and their site said that they "may be vulnerable".

So I suspect it reports that it MAY be vulnerable since it's unable to check whether it is. It could be that it knows how to check this for web servers but not for mail servers.

The POODLE and TLS 1.0-1.2 combination was discussed in OpenSSL mailing lists in 2014 and there the developers stated that the OpenSSL implementation which hMailServer use is not affected. The vulnerability was not in the protocol itself, but with a specific implementation made by another company.

https://mta.openssl.org/pipermail/openssl-users/2014-December/000021.html

So considering the OpenSSL developers says it's not affected, and Google's email server is also reported as "may be vulnerable", I'm guessing it's a limitation in comodoca's test software.

**Comment by hack2root** [comment]
It is possble that you probably does not disable SSL 3.0 on your Windows Server registry entry? 

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client]
"DisabledByDefault"=dword:00000001

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client]
"DisabledByDefault"=dword:00000001

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server]
"Enabled"=dword:00000000
