### ISSUE TITLE
Admin password can be blank

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#263]
http://www.hmailserver.com/forum/viewtopic.php?f=21&t=31490

If the administrator password in the .ini is removed, then you can start the Admin GUI without a password, and presumably also run scripts, authenticating with a null password.

This is likely to affect remote administration too (including PHPWebAdmin)
hMailServer should at least disable remote login completely without a password.
Additionally it should probably list the password issue in the configuration warnings list.

I'd personally like to see more security, like two factor authentication for remote access including PHPWebAdmin, and some way to authenticate in scripts without using the administrator password, and that being shown in clear text in the scripts. Scripts should be limited to only the local machine...

**Comment by martinknafve** [comment]
Nothing will be done with this in the near future due to lack of time. The installation wizard forces you to type in a password, so this is only an issue if you manually configure an empty password.

If an attacker gets access to your server and can change the contents of the Program Files directory, you're screwed anyways.

I understand that this is not optional, but this is far enough on the prio list that I won't do anything to change this in the near future.
