### ISSUE TITLE
Add TLS 1.3 support and switch to openssl 1.1.1 branch

### ISSUE THREAD

**Issue by raidensnake** [hmailserver/hmailserver#271]
Since TLS 1.3 is now released as a full protocol it would be good to enable support for it.

**Comment by Dravion** [comment]
Hi Raidensnake,
Unfortently, the OpenSSL Team has decided to break compatibility with the previes 1.0.2.x branch.
hMailServer code has to be changed to meet the new API requirements, which is not easy. 
On the other side hMailServer builts fine with LibreSSL instead of OpenSSL 1.1..x which is more secure
and well maintained (proactive security, strong and modern cyphers, memory protection techniques and 
secure random number generator). It Supports allready TLS 1.2 and the Team is working to get TLS 1.3
ready for primetime. ps: Even the latest Windows 1809 which is right now in Deployment doesnt Support TLS 1.3 (which affects MS-Exchange, SQL-Server, Outlook and Win10 MailApp). There are simply not many Clients supporting TLS 1.3 right now, so we dont need to hurry about it right now.

**Comment by martinknafve** [comment]
This is something I've started to work on now. Dravion mentions up code changes and API changes, but so far I've only run into a few lines of code which needed to be updated. So I'll at least try and change this and see if it works.

**Comment by raidensnake** [comment]
Thanks for the replies sorry if it was a few months but I'm glad this is being implemented.

**Comment by raidensnake** [comment]
Also I'd suggest disabling xp support as it's been discontinued by Microsoft. Even the pos version.

**Comment by mstenz** [comment]
I don't think XP support should be dropped because only of this reason. As long there is no change in hmailserver code that doesnt want to work on XP i don't see any reason why it should be removed from the list. Everyone should know the security risk of a discontinued Operating System.

**Comment by raidensnake** [comment]
@mstenz No offence but the reason I mentioned dropping support is mainly for 2 reasons. 1. If you use a server that has any form of compliancy it would fail instantly like PCI etc due to the ciphers like anything below TLS 1.2 being an instant failure under PCI 4.1 standards. Also the other reason is due to GDPR and other laws insecure ciphers are prohibited in certain countries now.

**Comment by martinknafve** [comment]
As far as I can tell, the suggestion to drop support for XP doesn't have anything to do with TLS 1.3/OpenSSL support. You can disable ciphers/TLS-versions as required by your organization and for example only run 1.3. Also, if some PCI auditor thinks that email sent to/from an organization is encrypted because their email servers supports TLS 1.2, they have probably understood how email encryption works. 

Also, dropping support for an OS in a patch-version is not a good idea. I think it will be dropped for 5.7 though, since it will only support x64 and I'm not going to spend time on setting up a 64-bit XP test environment.

**Comment by raidensnake** [comment]
@martinknafve Is it possible to add ocsp stapling?

**Comment by martinknafve** [comment]
OSCP stapling won't be added at this time. TLS1.3/openssl 1.1.1 is available for 5.6 now, so closing this issue.
