### ISSUE TITLE
Priority of emails to top of queue

### ISSUE THREAD

**Issue by cblaze22** [hmailserver/hmailserver#281]
This seems like a perfect and simple feature to add to HMailServer.  It would required reading an email header for these items and sorting them in the queue based on them.  

If normal emails dont have them then they are neutral, if emails come in when the queue is 4000 and has say the Importance: High header, then it should go to the top of the queue.

X-Priority: 1 (Highest)
X-MSMail-Priority: High
Importance: High

Is this something that can be added in for the next release?

**Comment by mstenz** [comment]
hi cblaze22, 
the Importance or Priority does not mean it need to be delivered in priority. This flag is just for the reader of the email to see if the CONTENT of the email is important to him or not. 
in the delivery of the email this is the same for all emails. this is quite important as otherwise everyone would just mark their email with "importance" to get it delivered faster. 
You need to make sure your server is able to process the queue real time if possible.

**Comment by cblaze22** [comment]
I see.  If you believe there is a header or something that could tag an email to be brought to the front of the queue let me know.  We had 7000 emails in a queue and they were basic notifications that someone can get anytime within the hour, but someone resetting their password shouldnt have to wait 30 min to get it before the whole queue processes.   There has to be some sort of priority of some sort on incoming emails to be sent out.

**Comment by mstenz** [comment]
> We had 7000 emails in a queue

> someone resetting their password shouldnt have to wait 30 min

Was this a temporary action because you used a script and send mass emails or is this normal behaviour in your server? If temporary you can ignore it, if your queue is full always and it really takes 30 minutes to process the queue you should increase the asynchronous processing threads HM is using. if you have a machine that does not allow this maybe your hardware specs are too low to run in your case. 
If you use any scripts to send emails best is to send them not all at the same time to overcome queuing issues or use a temporary different HM running on other port (for sending emails you don't need a port 25 listening) that does not block your normal queue.

**Comment by cblaze22** [comment]
This is common, we are a tournament management platform so game notificiations go our and evnet directors may send a bulk email out during the event.  We could have 150 events per weekend so you can only imagine.

We did update the async threads to 25 for a 2CPU machine with 7G of ram.  I am not sure what the best practice is on this or if there is a formula you would recommend.  We wouldnt mind increasing the CPU but of course that would cost us more money.

I looked into installing a second instance but the forum had mixed feedback if it was a good idea or not.  It would be nice if there was an article written up about that because it is a solution but what are the caveats and process of doing that.

In anycase adding priority to emails doesnt seem that far fetched to do or radical, installing another instance to accomplish just this does.

**Comment by mstenz** [comment]
> I looked into installing a second instance but the forum had mixed feedback if it was a good idea or not. It would be nice if there was an article written up about that because it is a solution but what are the caveats and process of doing that.

I am not sure if there exist any documentation about it (at least not for HM) but maybe you search for google about "mass sending email best practices". In regards of your specific installation it sould mean to create a 2nd hmailserver installation either on the same machine or a different lower machine (because this emails are not critical), you also need to configure some basic settings but you don't need to have any incoming ports for external (nondeliverable and any back coming email will go the main server). You can create a non-ssl incoming port that is listening internally only for your scripts that send the email. For me personally thats the normal way of sending mass emails.

**Comment by cblaze22** [comment]
I still think its risky to do a second install.  If it was verified only changing the port to it was the answer I may do it.  

Do you know what the logic is in terms of marking an email as "send now" through the queue.  Is there a flag attached to that email?  I may need to modify the code myself to mark an email as "send now" if they have a priority flag.

**Comment by mstenz** [comment]
> Do you know what the logic is in terms of marking an email as "send now" through the queue.

Emails would be send 1 by 1 from the top of the queue. the more threads you have the faster it will be. So for non-critical emails like mass emails a seperate system would be ideal.

**Comment by OutbackMatt** [comment]
Why is a second (stand alone) instance risky?
Using the one database and data folders set may be, but they could easily be independent machines

**Comment by martinknafve** [comment]
This won't be added anytime soon (mainly due to prio / lack of time), so I'll close this request without action.

**Comment by mstenz** [comment]
One thing to add as I have just found it. 
It seems Facebooks email delivery system have some type of priorization: 
https://heidemann.it/blog/it/zuckmail-der-facebook-email-client
there is the X-FACEBOOK-PRIORITY header. i have seen 0 on chat messages, 1 on new comments in groups, don't know of any other but i assume some "email2all" will get higher number which means lower priority.
