### ISSUE TITLE
Function in webadmin is deprecated

### ISSUE THREAD

**Issue by Virinum** [hmailserver/hmailserver#307]
I'm getting this error in webadmin running on PHP 7.4.0
![screenshot](https://user-images.githubusercontent.com/42373861/70029969-7df33000-15a8-11ea-874b-a890b14571f6.PNG)

because of this deprecated function call
https://github.com/hmailserver/hmailserver/blob/62066f6ceaa6c35f00600b060a943c766f4adc81/hmailserver/source/WebAdmin/include/functions.php#L33

**Comment by visualperception** [comment]
I would go back to PHP 7.3.12 as the get_magic_quotes_gpc() function was deprecated in the very latest version of PHP.
It is not always wise to use latest version of any released software.
No doubt someone will update the code in due course as that function always returns false anyway. i.e. it performs no useful purpose in version 7.x.x. of PHP

OR

you can try the following as a  simpler fix:

change the following lines functions.php 

	if (get_magic_quotes_gpc())
		$retval = stripslashes($retval);

to

//	if (get_magic_quotes_gpc())
//		$retval = stripslashes($retval);



I tried this on my versoin and it seems to work OK but there are no guarantees since I'm running an older version of PHP.

**Comment by martinknafve** [comment]
The use of this function has been removed and will no longer be in use in the latest build.
