### ISSUE TITLE
How to correctly edit \Windows\System32\drivers\etc\hosts file

### ISSUE THREAD

**Issue by JanuszChmiel** [hmailserver/hmailserver#329]
Dear specialist,
I Am visually impaired WIndows 10 Home Edition user and I would like to know, how to correctly edit The 
\Windows\System32\drivers\etc\host
 file
The two last lines of this files are
#	::1             localhost
localhost.com

Are those lines correct? My goal is to try yours SMTP server as A local host. If it will be possible to post E-mail by using it with some E-mail client.
GUI is perfectly accessible with screen reader, thank you very much for that. 
Thank you very much for yours advice

**Comment by mstenz** [comment]
You need to top open the editor with Administrator rights (right mouse click) and then you can edit the file. 
I would assume the entry is not correct, but also your paste is wrong. please use github code/quote methods to paste content of files. 
Even you may be able to run hmailserver on your machine, if you are running on a normal private internet line most probably you cannot send (or maybe also not receive) email because this is blocked by either your IPS and/or blacklists.

**Comment by mstenz** [comment]
Please note that the issue feature here is not about asking questions, i assume you can get more help in hmailserver forum.

**Comment by JanuszChmiel** [comment]
Thank you very much. So even if I would setup app correctly, server
administrator of ISP can block The server from sending E-mails. Yes, many
smtp servers from various E-mail box providers are blocking
chmiel@localhost.com so I can not try The pop3 feature.
But thank you very much for yours help.

**Comment by mstenz** [comment]
> E-mail box providers are blocking
chmiel@localhost.com so I can not try The pop3 feature.

Anyhow i assume chat localhost.com is not owned by you?!?

**Comment by JanuszChmiel** [comment]
Oh I Am amateur. I would had to buy some domain first.
Do not be afraid, I will stop to bother you. Yours server is perfect but it
would require to use Interanet on some university not private VDSL
connection. Thank you very much for yours patience with Me.
