### ISSUE TITLE
Is and will hmailserver be actively developed?

### ISSUE THREAD

**Issue by Amityville-DE** [hmailserver/hmailserver#350]
Hi everyone,

I just found out about this awesome project. I wanted to ask if the project will get support for the next years?
Since the last stable version is from 2017 (beta from 05/2020). Please do not misunderstand my question, I just want to be sure before using hmailserver in production.

Also the documentation says, that Windows Servers up to 2016 are supported, what about 2019?

Thanks in advance!

**Comment by visualperception** [comment]
It is open source so anyone can update it. I suspect Martin, the developer, is busy with other things at present and I don't know what the tme lines are . However, I know he has been working on a 64 bit version as the next major release, it is in Beta ( maybe Alpha ) at present.
You might try asking this question at the main forum, which you can find at: https://www.hmailserver.com/forum/

**Comment by JPVenson** [comment]
Infrequent is an understatement. According to the download page the last stable release is 5.6.7 and it is already 2 years and 11 months old. For such an exposed application like a mail server I cannot imagine how many potential security holes are in the OpenSSL lib alone. No offence I maintain some OSS projects myself and I know that it is not his "job" but that is such a timespan that you say that it is "active". I saw that there are some contributions but no active release means that I would not say this is in any way usable for a live production.

**Comment by OutbackMatt** [comment]
Since that date, every release of OpenSSL has seen a 'beta release'

Since that date, Martin has also moved the source here (Github), and the build mechanism now uses the github build processes.

Some have forked the source, and RvdHout is building the official source builds.

if you look in actions, then click on any result, you can download the artifacts (if you are logged in)
Most recent was 31 October 2020, less than 2 weeks ago.

These are builds of the 5.7 branch which is 64 bit, and really should be considered alpha, but some of us (me included) use them in production.

Rvvd also posts some updated builds in the user forum of the 5.6.X branch which is 32 bit.

There are a few other developers putting together custom builds.

This project is more than 20 years old, and sure Martin doesn't come around as much as we like, but at least we can still develop this product, fix issues, and add new features.
Rvvd also

**Comment by martinknafve** [comment]
See https://www.hmailserver.com/forum/viewtopic.php?f=8&p=236006#p235992
