### ISSUE TITLE
archiving occupy large disk space?

### ISSUE THREAD

**Issue by andrewchenshx** [hmailserver/hmailserver#403]
(1)more then 300000 mails.
(2)in outlook2013, the pst file is less then 30GB.
(3)set up HMailserver, connect  outlook2013 to it with IMAP.
(4)move all the mails to the inbox, the local outlook file(ost) occupies about 50GB.
(5)connect thunderbird to HMailserver, and archive the mails in the inbox.
the data directory occupies more and more disk space with archiving operation. 
it's now 130GB.

**Comment by martinknafve** [comment]
I'm not sure what the question is here. Is your question why the hMailServer data directory is so large after your operations?

You mentioned that your Outlook file was 30GB. Then you copied messages to hMailServer and it was 50GB. That sounds like an Outlook issue rather than an hMailServer issue, right?

When you remove messages using Thunderbird, often it marks them as deleted but don't actually delete the data. Have you compacted the folders?

**Comment by andrewchenshx** [comment]
finally i found there were too many duplicated emails.
i got a sript to delete it.
