### ISSUE TITLE
Certificate expired but no errors

### ISSUE THREAD

**Issue by howlettt** [hmailserver/hmailserver#432]
The certificate we were using with hmailserver expired but we didn't get any errors reported in the logs, most emails just weren't sent and oddly a few still went through. All we saw in the logs is the following

```
"RECEIVED: STARTTLS"
"SENT: 220 Ready to start TLS"
"SENT: 220 xxxxxx.net ESMTP"
"RECEIVED: EHLO"
"SENT: 250-xxxxxx.net[nl]250-SIZE 40960000[nl]250-STARTTLS[nl]250-AUTH LOGIN[nl]250 HELP"
```

**Comment by martinknafve** [comment]
Most email servers does not care about the validity of the certificate. You can configure your email server to use a certificate with invalid host name which expired in the 1980's and other servers will ignore it.

Note that the cert you configure in hMailServer is used for inbound traffic. The logs you posted shows that a handshake was performed and the sender then proceeded with sending the email. That is expected, since most email servers ignore the validity.
