### ISSUE TITLE
Remove collection of statistics

### ISSUE THREAD

**Issue by martinknafve** [hmailserver/hmailserver#435]
hMailServer has logic to collect statistics. This statistics is no longer used, so the logic should be removed.

**Comment by chrissawyerfan4** [comment]
Internet archive says this page hasn't updated since 2020, but the old stats are still visible for anyone curious: https://www.hmailserver.com/statistics/ (IA refuses to do a new capture because it times out, btw.)

When was the statistics collector removed on the website side? And why, it seems like fun to me to collect these
