### ISSUE TITLE
MESSAGE object in Com API not conforming to RFC on

### ISSUE THREAD

**Issue by OutbackMatt** [hmailserver/hmailserver#73]
As per forum posts
https://www.hmailserver.com/forum/viewtopic.php?f=10&t=27606

I'm not sure that this is a real issue.

MattG

**Comment by martinknafve** [comment]
The From property of the message gets and sets the From header in the email message. While the From header must have a specific format according to the RFC, there's nothing preventing anyone from sending email messages with incorrectly formatted headers. This happens all the time.

So if a message is received with an incorrectly formatted From header, there are two options:

- The From property in the API could return the incorrectly formatted data
- The From property in the API could return an empty string, or throwing an exception that the data is invalid

I've chosen the first alternative here, because I believe it makes the API easiest to work with.

It would be weird if the From property could return specific data, but you would not be able to set the same yourself. As a consequence, the From property can return incorrectly formatted data, and you can give it incorrectly formatted data.

So I'll close this without action.
