### ISSUE TITLE
[enhancement] Allow Wildcard Mailboxes

### ISSUE THREAD

**Issue by igal-getrailo** [hmailserver/hmailserver#76]
It'd be great if we could create a mailbox with a wildcard, e.g.  `bounce-*@mydomain.org`, which will catch everything that matches that signature.

This is a very important feature, as it can allow for checking out bounced addresses, so that you can set the bounce-to address with an ID, e.g. bounce-54321@mydomain.org and then you can check later which emails bounced.

I currently do not use hmailserver, but if it had that feature I would definitely give it a try.

**Comment by martinknafve** [comment]
This sounds like plus addressing which hMailServer already supports.



----- Ursprungligt meddelande -----
Från: "Igal" <notifications@github.com>
Skickat: ‎2015-‎01-‎16 21:03
Till: "hmailserver/hmailserver" <hmailserver@noreply.github.com>
Ämne: [hmailserver] [enhancement] Allow Wildcard Mailboxes (#76)

It'd be great if we could create a mailbox with a wildcard, e.g. bounce-*@mydomain.org, which will catch everything that matches that signature.
This is a very important feature, as it can allow for checking out bounced addresses, so that you can set the bounce-to address with an ID, e.g. bounce-54321@mydomain.org and then you can check later which emails bounced.
I currently do not use hmailserver, but if it had that feature I would definitely give it a try.

**Comment by igal-getrailo** [comment]
Thank you for your prompt response.  I was not aware of that.
