### ISSUE TITLE
SMTP Connections did not free up after connection lost

### ISSUE THREAD

**Issue by Michamicha** [hmailserver/hmailserver#99]
Under certain conditions SMTP Sessions are not cleared correctly, eating up all available slots (up to 25 in my case).

This happens when connected with SSL on Port 465 and then interrupt the connection right after TLS/SSL Handshake completed and maybe (not tested) with unencrypted connections to port 25.

For replication of this behaviour connect with telnet to a ssl smtp port and simply close the telnet window. This kills the connection but HMS does not recognize. When this happens 25 times, all available smtp slots are open, thus nobody can connect anymore.

This can easily be used for Denial-of-Service attacks even if SMTP connection limit is set to unlimited as each new smtp connection will eat up server memory.

See here for discussion: https://www.hmailserver.com/forum/viewtopic.php?f=7&t=28098.

**Comment by martinknafve** [comment]
I could not immediately reproduce. Since there's an ongoing discussion in the forum I'll post there.

**Comment by martinknafve** [comment]
Just for your info - the fix I just commited to this issue is kind of related to your issue, but it's not the issue you are experiencing. This fix is for when Windows fails to determine that the connection has been closed. In your case, Windows has determined that the connection is closed, but for some reason it's still active in hMailServer. So two different issues, albeit related.

**Comment by martinknafve** [comment]
Resolved in 5.6.4
